name: "Configure AWS Region"
description: "Receives AWS Region and output it"
inputs:
  region:
    description: 'AWS Region to Deploy'
    required: true
    default: 'ap-southeast-1'
  name:
    description: "stack name"
    required: true
    default: 'ec2-test-stack'
  template:
    description: "template"
    required: true
    default: 'ec2.yaml'
outputs:
  region: # id of output
    description: "AWS Region to deployed"
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.region }}.
      shell: bash