name: "Configure AWS Region"
description: "Receives AWS Region and output it"
inputs:
  region:
    description: 'AWS Region to Deploy'
    required: true
    default: 'ap-southeast-1'
outputs:
  region: # id of output
    description: "AWS Region to deployed"
runs:
  using: "composite"
  steps:
    - run: echo "ap-southeast-1" ${{ inputs.region }}.
      shell: bash

    