Mappings:
  RegionEC2InstanceImageMap:
    us-east-2:
      HVM64: ami-02de934ca4f3289e0 
      HVM32: ami-0233c2d874b811deb
    ap-southeast-1:
      HVM64: ami-0390917f7df0de28c
      HVM32: ami-0e5182fad1edfaa68

Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      ImageId: !FindInMap
        - RegionEC2InstanceImageMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref EC2InstanceType