Parameters:
  EC2InstanceType:
    Description: The Instance Type Chosen for EC2
    Type: String
    Default: t2.micro
    
Resources:
  TekLoonTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-1a
      ImageId: ami-065383d02b8c40ff8
      InstanceType: !Ref EC2InstanceType