name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    # needs: [continuous-integration]
    # if: github.ref == 'refs/heads/main'
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-southeast-1
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws cloudformation deploy --template-file ./ec2.yaml --stack-name ec2-new-stack
          