name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: self-hosted
    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ap-southeast-1
     # Step 2
      - name: Deploy Cloudformation Template
        id: deploy
        run: |
          pwd          
          cd /home/jgooco/actions-runner/_work/aws-cloudformation-ec2/aws-cloudformation-ec2/
          aws cloudformation deploy \
            --template-file /home/jgooco/actions-runner/_work/aws-cloudformation-ec2/aws-cloudformation-ec2/ec2.yml \
            --stack-name ec2-new-stack

          